const API_BASE_URL = import.meta.env.VITE_API_BASE_URL?.replace(/\/+$/, "") || "https://api.unxlabs.xyz";

export interface AdminTierDistribution { tier_key:string; tier_name:string; holders:number; passes:number }
export interface AdminOverviewResponse { success:true; authenticated:true; authorized:true; admin:{role:"admin"|"super_admin"}; generatedAt:number; periods:{todayTimezone:string;sevenDays:string;thirtyDays:string}; users:{total:number;newToday:number;new7d:number;new30d:number;active7d:number;active30d:number}; wallets:{total:number}; genesis:{holders:number;passes:number;tierDistribution:AdminTierDistribution[]} }
export interface AdminUserItem { userId:string; username:string|null; status:string; createdAt:number; lastActiveAt:number; wallet:{address:string;status:string;connectedAt:number;lastSeenAt:number}; genesis:{balance:number;tierKey:string;tierName:string;syncedAt:number|null} }
export interface AdminUsersResponse { success:true; authenticated:true; authorized:true; admin:{role:"admin"|"super_admin"}; total:number; limit:number; offset:number; users:AdminUserItem[] }
export interface AdminWalletDetailResponse { success:true; authenticated:true; authorized:true; user:{userId:string;username:string|null;status:string;createdAt:number;lastActiveAt:number}; wallet:{address:string;status:string;connectedAt:number;lastSeenAt:number}; genesis:{balance:number;tierKey:string;tierName:string;syncedAt:number|null}; balances:{BNB:{raw:string;formatted:string};USDT:{raw:string;formatted:string};BTCB:{raw:string;formatted:string}}; balanceSource:string; generatedAt:number }

export class AdminApiError extends Error { status:number; constructor(message:string,status:number){super(message);this.name="AdminApiError";this.status=status} }
async function api<T>(path:string):Promise<T>{ const response=await fetch(`${API_BASE_URL}${path}`,{method:"GET",credentials:"include",headers:{Accept:"application/json"}}); let data:unknown; try{data=await response.json()}catch{throw new AdminApiError("The API returned an invalid response.",response.status)} if(!response.ok){const body=data as {error?:string};throw new AdminApiError(body?.error||(response.status===401?"Sign in with an authorized wallet.":response.status===403?"This account does not have admin access.":"Unable to load admin data."),response.status)} return data as T }
export const getAdminOverview=()=>api<AdminOverviewResponse>("/admin/overview");
export function getAdminUsers(params?:{search?:string;tier?:string;status?:string;limit?:number;offset?:number}){const q=new URLSearchParams();if(params?.search)q.set("search",params.search);if(params?.tier)q.set("tier",params.tier);if(params?.status)q.set("status",params.status);q.set("limit",String(params?.limit??50));q.set("offset",String(params?.offset??0));return api<AdminUsersResponse>(`/admin/users?${q}`)}
export const getAdminWallet=(address:string)=>api<AdminWalletDetailResponse>(`/admin/wallets/${encodeURIComponent(address)}`);
